"""mysql database

Revision ID: 8751d95482b6
Revises: 
Create Date: 2021-06-15 13:54:36.618008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8751d95482b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'body',
               existing_type=mysql.VARCHAR(length=140),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('comment', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('comment', 'post_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('comment', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('comment', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.drop_table_comment(
        'comment',
        existing_comment='TRIAL',
        schema=None
    )
    op.drop_column('comment', 'trial608')
    op.alter_column('followers', 'followed_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('followers', 'follower_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.drop_table_comment(
        'followers',
        existing_comment='TRIAL',
        schema=None
    )
    op.drop_column('followers', 'trial621')
    op.alter_column('post', 'body',
               existing_type=mysql.VARCHAR(length=140),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('post', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('post', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('post', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.drop_table_comment(
        'post',
        existing_comment='TRIAL',
        schema=None
    )
    op.drop_column('post', 'trial624')
    op.alter_column('postlike', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('postlike', 'post_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('postlike', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.drop_table_comment(
        'postlike',
        existing_comment='TRIAL',
        schema=None
    )
    op.drop_column('postlike', 'trial631')
    op.alter_column('user', 'about_me',
               existing_type=mysql.VARCHAR(length=140),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'last_seen',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='TRIAL',
               existing_nullable=True)
    op.drop_table_comment(
        'user',
        existing_comment='TRIAL',
        schema=None
    )
    op.drop_column('user', 'trial637')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('trial637', mysql.CHAR(length=1), nullable=True, comment='TRIAL'))
    op.create_table_comment(
        'user',
        'TRIAL',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'last_seen',
               existing_type=mysql.DATETIME(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('user', 'about_me',
               existing_type=mysql.VARCHAR(length=140),
               comment='TRIAL',
               existing_nullable=True)
    op.add_column('postlike', sa.Column('trial631', mysql.CHAR(length=1), nullable=True, comment='TRIAL'))
    op.create_table_comment(
        'postlike',
        'TRIAL',
        existing_comment=None,
        schema=None
    )
    op.alter_column('postlike', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('postlike', 'post_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('postlike', 'id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('post', sa.Column('trial624', mysql.CHAR(length=1), nullable=True, comment='TRIAL'))
    op.create_table_comment(
        'post',
        'TRIAL',
        existing_comment=None,
        schema=None
    )
    op.alter_column('post', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('post', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('post', 'id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('post', 'body',
               existing_type=mysql.VARCHAR(length=140),
               comment='TRIAL',
               existing_nullable=True)
    op.add_column('followers', sa.Column('trial621', mysql.CHAR(length=1), nullable=True, comment='TRIAL'))
    op.create_table_comment(
        'followers',
        'TRIAL',
        existing_comment=None,
        schema=None
    )
    op.alter_column('followers', 'follower_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('followers', 'followed_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.add_column('comment', sa.Column('trial608', mysql.CHAR(length=1), nullable=True, comment='TRIAL'))
    op.create_table_comment(
        'comment',
        'TRIAL',
        existing_comment=None,
        schema=None
    )
    op.alter_column('comment', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('comment', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=True)
    op.alter_column('comment', 'id',
               existing_type=mysql.INTEGER(),
               comment='TRIAL',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('comment', 'body',
               existing_type=mysql.VARCHAR(length=140),
               comment='TRIAL',
               existing_nullable=True)
    # ### end Alembic commands ###
